# Generated by Django 5.1.5 on 2025-04-20 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='job_ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('job_location', models.CharField(max_length=255)),
                ('job_min_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('job_max_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stress_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=255)),
                ('is_full_time', models.BooleanField(default=False)),
                ('is_part_time', models.BooleanField(default=False)),
                ('is_internship', models.BooleanField(default=False)),
                ('auditory_score', models.FloatField(blank=True, null=True)),
                ('visual_score', models.FloatField(blank=True, null=True)),
                ('tactile_score', models.FloatField(blank=True, null=True)),
                ('communication_score', models.FloatField(blank=True, null=True)),
                ('job_status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed')], default='draft', max_length=10)),
                ('publish_status', models.CharField(max_length=50)),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
