# Generated by Django 5.1.5 on 2025-04-20 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employerQuestion', '0001_initial'),
        ('jobApplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='applicant_answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='jobApplication.job_application')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='employerQuestion.employer_question')),
            ],
        ),
    ]
