# Generated by Django 5.1.5 on 2025-04-20 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobAd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employer_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.IntegerField()),
                ('question_ux_id', models.CharField(max_length=255)),
                ('job_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='jobAd.job_ad')),
            ],
        ),
    ]
